SELECT * FROM PIZZA_SALES;

-- KPI
-- 1. TOTAL REVENUE

SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES;

-- 2. TOTAL ORDERS
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES;

-- 3. AVERAGE ORDER VALUE
SELECT CAST(CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) /
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) AS DECIMAL(10,2)) 
AS AVG_ORDER_VALUE
FROM PIZZA_SALES;

--4. TOTAL PIZZAS SOLD
SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM PIZZA_SALES;

--5. AVERAGE PIZZAS PER ORDER
SELECT CAST(CAST(SUM(QUANTITY) AS DECIMAL(10,2))/
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2))
AS DECIMAL(10,2)) AS AVG_PIZZA_PER_ORDER FROM PIZZA_SALES;

SELECT * FROM PIZZA_SALES;
--ANALYSIS
-- 1. Monthly Trend for Total Revenue
SELECT DATENAME(MONTH,ORDER_DATE) AS MONTH, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY DATENAME(MONTH,ORDER_DATE);

-- 2. Daily Trend for Total Orders
SELECT datename(WEEKDAY,ORDER_DATE) AS DAY, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY datename(WEEKDAY,ORDER_DATE);

--3. Percentage of Sales by Pizza Category
SELECT pizza_category, 
CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) as Total_Revenue,
cast(SUM(TOTAL_PRICE) * 100
/(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES) as decimal(10,2))
as Percentage_Pizza_Catgy
FROM pizza_sales
GROUP BY pizza_category;


--4.Percentage of Sales by Pizza Size
SELECT pizza_size, 
CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) as Total_Revenue,
cast(SUM(TOTAL_PRICE) * 100
/(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES) as decimal(10,2))
as Percentage_Pizza_size
FROM pizza_sales
GROUP BY pizza_size;

-- 5.Total Pizzas Sold by Pizza Size and Category
SELECT pizza_size, SUM(quantity) as Total_Sold_Size
FROM pizza_sales
GROUP BY pizza_size;

SELECT pizza_category, SUM(quantity) as Total_Sold_Categy
FROM pizza_sales
GROUP BY pizza_category;


-- 6. Revenue by Pizza Name
SELECT TOP 5 PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE ;


-- Top & Bottom Analysis

-- 1. Top Pizza by Revenue
SELECT TOP 5 PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE DESC;

-- 2. Bottom Pizza by Revenue
SELECT TOP 5 PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE ASC;

-- 3. Top Pizza by Orders
SELECT TOP 5 PIZZA_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS DESC;

-- 4. Bottom Pizza by Orders
SELECT TOP 5 PIZZA_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS ASC;

-- 5.Top Pizza by Quantity Sold
SELECT TOP 5 PIZZA_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY DESC;

-- 6.Bottom Pizza by Quantity Sold
SELECT TOP 5 PIZZA_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY ASC;